package com.example.aidong.common;


import com.example.aidong.BaseUrlLink;

public class UrlLink extends BaseUrlLink {
	public static final String VERSIONDETECTION_URL = URL + "deploy/ver";
	public static final String ICON_URL = URL +"deploy/icon";
	public static final String CAPTCHACHECK_URL = URL + "captcha/check";
	public static final String CAPTCHACHANGE_URL = URL + "captcha/change";
	public static final String FEEDBACK_URL = URL + "business/feedback";
	public static final String FEEDBACK = URL + "feedback";
	public static final String CHANGEPASSWORD_URL = URL + "business/login";
	public static final String LOGIN_URL =URL + "users/login";
	public static final String CHANGEPASSWORD = URL + "users";
	public static final String FIND = URL + "find";
	public static final String TALENTURL = URL + "api/talent";
	public static final String SPEICALSTOREHOME_URL = URL + "shop";
	public static final String EVERYDAYBAOKUAN_URL = URL + "shop/recommends/course";
	public static final String PRACTICE_URL = URL + "shop/recommends/buy";
	public static final String PRIVATECOACH_URL = URL + "shop/recommends/coach";
	public static final String BINGDINGIPHONE = URL + "captcha/binding";
	public static final String WALLETDETAIL_URL = URL +"mine/wallet/detail";
	public static final String CUSTOMERSERVICEPHONE_URL = URL + "deploy/service";
	public static final String WALLET_URL = URL +"mine/wallet";
	public static final String COUPONS_URL = URL + "mine/wallet/coupons";
	public static final String DUIHUANCOUPON_URL = URL + "mine/wallet";
	public static final String SIGNMEIDOU_URL = URL + "sign";
	public static final String NEWACTIVITY_URL = URL + "find/events/top";
	public static final String FINDGALLARY_URL = URL + "find/gallery";
	public static final String FRIENDS_URL = URL + "friends";
	public static final String NEWS_URL = URL + "discovery/news";
	public static final String GROUPS_URL = URL + "groups";
	public static final String GROUPS_MINE_URL = URL + "groups/mine";
	public static final String BUNNER_URL = URL + "deploy/banner";
	public static final String COMMENTS_URL = URL + "comments";
	public static final String DELETE_DYNAMIC_URL = URL + "dynamics/";
	public static final String PERSONALDATA_IRL = URL + "profile";
	public static final String MYSHOWVIEDOE_URL = URL + "showtime";
	public static final String MYSHOWPHOTOWALL_URL = URL + "photos";
//	public static final String MYSHOWDYNAMICS_URL = URL + "dynamics";
	public static final String MYSHOWDYNAMICS_URL = URL + "api/dynamics";
	public static final String DYNAMICZAN_URL = URL + "likes/dynamic";
	public static final String ZANPENRSON_URL = URL + "likes/person";
	public static final String LIKES_URL = URL + "likes";
	public static final String COURSEOFATTENTION_URL = URL + "mine/concerns";
	public static final String GYMSCOURSES_URL = URL + "gyms/courses";
	public static final String AGENCYCOURSES_URL = URL + "agency/courses";
	public static final String GYMSCOACHCOMMENTS_URL = URL + "gyms/coach/comments";
	public static final String PRIVACY_URL = URL + "mine/setting";
	public static final String NOTFINISHED_URL = URL + "mine/classes/incomplete";
	public static final String YESFINISHED_URL = URL + "mine/classes/complete";
	public static final String CLASSESDETAIL_URL = URL + "mine/classes/incomplete/detail";
	public static final String MINEORDERS_URL = URL + "mine/orders";
	public static final String NOTFINISHEDDETAILS_URL = URL + "mine/classes/incomplete/detail";
	public static final String GROUPPHOTOS_URL = URL + "group_photos";
	public static final String GROUPPHOTOSDE_URL = URL + "group_photos/";
	public static final String UPDATEGROUPS_URL = URL + "groups";
	public static final String REPORT_URL = URL + "report";
	public static final String OTHER_URL = URL + "friends";
	public static final String MINEORDERSSHOW_URL = URL + "mine/orders/show";
	public static final String NEWDYNAMIC_URL = URL + "dynamics/latest";
	public static final String SERVICESCOACHES_URL = URL + "services/coaches";
	public static final String DELETEPHOTOS_URL = URL + "photos";
	public static final String UPLOADPHOTOS_URL = URL + "photos";
	public static final String CAPTCHA_URL = URL + "captcha/regist";
	public static final String USERSLOGIN_URL = URL + "users/login";
	public static final String GPSCITY_URL = URL + "deploy/city";
	public static final String SHOPCOURSES_URL = URL + "shop/courses";
	public static final String YIGOUSTUDENT_URL = URL + "shop/buyers";
	public static final String COMMODITYREIEW_URL = URL + "shop/comments";
	public static final String DYNAMICSLATEST_URL = URL + "dynamics/latest";
	public static final String LOGINSNS_URL = URL + "users/sns";
	public static final String ADDLISTFRIEDNDS_URL = URL + "friends/search";
	public static final String LOGOUT_URL = URL + "users";
	public static final String MINECLASSESCOMMENT_URL = URL + "mine/classes/comment";
	public static final String active_URL = URL + "active";
	public static final String auto_login = URL + "auto_login";
	public static final String FIND_UPLOAD_URL = URL + "find/upload";
	public static final String ROB_COUPONS = URL + "shop/coupons";
	public static final String HELP_COUPONS = URL + "shop/coupons/help";
	public static final String FOUND_DISCOVERY = URL + "discovery/images";
	public static final String UNPROCESSED_URL = URL + "mine/orders/unprocessed";
	public static final String PRIVATE_DETAIL= URL + "api/gyms/profile";
	public static final String HOME_PAGE= URL + "api";
	public static final String HOT_SEARCH= URL + "api/hot";
	public static final String VENUES_LIST= URL + "api/venues";
	public static final String FANPERSONALDATA_IRL = URL + "api/fan/profile";
	public static final String VENUESPERSONALDATA_IRL = URL + "api/venues/profile";
	public static final String API_SEARCH= URL + "api/search";
	public static final String SHOW_VENUES= URL + "api/boutique";
	public static final String KNOWLEDGE_UPNDAY= URL + "api/knowledge";
	public static final String LOOK_PRIVATE= URL + "api/gyms";
	public static final String ROB_COUPONS_API= URL + "api/coupon";
	public static final String ROB_COUPONS_GET= URL + "api/coupons";
	public static final String MINE_LIKES_MOST= URL + "mine/likes/most";
	public static final String MINE_LIKES_LATEST= URL + "mine/likes/latest";
	public static final String VENUES_RECOMMEND= URL + "api/recommend/venues";
	public static final String PRIVATE_LESSON= URL + "api/gyms/courses";
	public static final String PRIVATE_COMMENT= URL + "api/gyms/comments";
	public static final String FOUND_DYNAMIC= URL + "discovery/dynamics";
	public static final String PERSON_DYNAMIC= URL + "api/dynamics";
	public static final String API_COURSE= URL + "api/course";
	public static final String COURSE_NEWS_TOP= URL + "api/course/news/top";
	public static final String SEARCH_COURSE= URL + "api/course/search";
	public static final String MYCOUPON= URL + "mine/coupons";
	public static final String STRATEGY_LIST= URL + "api/course/strategies";
	public static final String VENUES_COACHES= URL + "api/venues/coaches";

	public static final String STRATEGY_COMMENT= URL + "api/course/strategies/comments";


	public static final String VENUES_COURSES= URL + "api/venues/courses";
	public static final String VENUES_COMMENTS_LATEST= URL + "api/venues/comments/latest";
	public static final String VENUES_COMMENTS= URL + "api/venues/comments";
	public static final String COURSE_DETAIL= URL + "api/course/show";
	public static final String BOOTSCREEN= URL + "deploy/ads";
	public static final String SELECT_COUPON= URL + "api/course/coupons";
	public static final String DYNAMIC_DETAIL= URL + "api/dynamics/show";

	public static final String COURSE_UPNDAY= URL + "api/course/news";
	public static final String FACE_TO_FACE_PAY= URL + "api/orders/";
	public static final String MINE_CARDS= URL + "mine/cards";
	public static final String ORGANIZATION_MEMBER_CARD= URL + "mine/";
	public static final String MINE_CARDS_EXPIRED= URL + "mine/cards/expired";
	public static final String MEMBER_SIGN_IN= URL + "mine/cards/";



}
